# Generated by Django 2.2.6 on 2019-10-22 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='updated_att',
            new_name='updated_at',
        ),
    ]
